apiVersion: v1
kind: Secret
metadata:
  name: zest-eats-delivery-secrets
  namespace: default
stringData:
  delivery-sql-connection: "Server=your_sql_server;Database=ZestEatsDelivery;User Id=your_user;Password=your_password;"
  kafka-bootstrap-servers: "your_kafka_bootstrap_servers"
