apiVersion: v1
kind: Secret
metadata:
  name: zest-eats-payment-secrets
  namespace: default
stringData:
  payment-sql-connection: "Server=your_sql_server;Database=ZestEatsPayments;User Id=your_user;Password=your_password;"
  razorpay-key-id: "your_razorpay_key_id"
  razorpay-key-secret: "your_razorpay_key_secret"
