apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 3 * * *" # daily at 3am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mongo
              command: ["/bin/sh", "-c"]
              args:
                - mongodump --uri=$MONGO_URI --out=/backup/$(date +%F)
              env:
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secrets
                      key: uri
              volumeMounts:
                - name: backup
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: mongodb-backup-pvc
