apiVersion: batch/v1
kind: CronJob
metadata:
  name: sqlserver-backup
spec:
  schedule: "0 2 * * *" # daily at 2am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mcr.microsoft.com/mssql-tools
              env:
                - name: MSSQL_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: sqlserver-secrets
                      key: SA_PASSWORD
              command: ["/bin/sh", "-c"]
              args:
                - /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -Q "BACKUP DATABASE [zesteats] TO DISK = '/backup/zesteats_$(date +%F).bak'";
              volumeMounts:
                - name: backup
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: sqlserver-backup-pvc
